"""
Generate MariaDB INSERT statements from the scraped MPL Indonesia JSON files.

Run from the repository root:
    python "Data Storing/src/make_seed.py"

Then load into MariaDB after schema.sql:
    mariadb -u root -p mpl_indonesia < "Data Storing/src/seed.sql"
"""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "Data Scraping" / "data"
OUT_FILE = Path(__file__).with_name("seed.sql")


def load_json(filename):
    return json.loads((DATA_DIR / filename).read_text(encoding="utf-8"))


def sql_value(value):
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace("\\", "\\\\").replace("'", "''")
    return f"'{text}'"


def insert(table, columns, rows):
    if not rows:
        return ""
    lines = [f"INSERT INTO {table} ({', '.join(columns)}) VALUES"]
    values = []
    for row in rows:
        values.append("  (" + ", ".join(sql_value(row[col]) for col in columns) + ")")
    return "\n".join(lines + [",\n".join(values) + ";", ""])


def main():
    seasons = load_json("seasons.json")
    teams = load_json("teams.json")
    players = load_json("players.json")
    team_seasons = load_json("team_seasons.json")
    rosters = load_json("rosters.json")
    awards = load_json("awards.json")
    matches = load_json("matches.json")

    team_id = {row["team_name"]: i for i, row in enumerate(teams, start=1)}
    person_id = {row["player_name"]: i for i, row in enumerate(players, start=1)}

    award_names = []
    seen_awards = set()
    for row in awards:
        name = row["award_type"]
        if name not in seen_awards:
            seen_awards.add(name)
            award_names.append(name)
    award_type_id = {name: i for i, name in enumerate(award_names, start=1)}

    season_location_rows = [
        {"season_number": row["season_number"], "location": location}
        for row in seasons
        for location in row["locations"]
    ]

    roster_rows = []
    roster_lookup = {}
    for row in rosters:
        key = (row["player_name"], row["season_number"], row["team_name"])
        if key in roster_lookup:
            raise RuntimeError(f"duplicate roster entry after cleansing: {row}")
        roster_lookup[key] = row
        roster_rows.append({
            "person_id": person_id[row["player_name"]],
            "season_number": row["season_number"],
            "team_id": team_id[row["team_name"]],
            "roster_status": row["status"],
            "roster_role": row["role"],
        })

    match_rows = []
    match_team_rows = []
    for i, row in enumerate(matches, start=1):
        match_rows.append({
            "match_id": i,
            "stage": row["stage"],
            "week": row["week"],
            "match_day": row["match_day"],
            "round_name": row["round_name"],
            "season_number": row["season_number"],
        })
        match_team_rows.extend([
            {
                "match_id": i,
                "team_id": team_id[row["team_a"]],
                "side": "A",
                "score": int(row["score_a"]),
            },
            {
                "match_id": i,
                "team_id": team_id[row["team_b"]],
                "side": "B",
                "score": int(row["score_b"]),
            },
        ])

    team_season_rows = [
        {
            "season_number": row["season_number"],
            "team_id": team_id[row["team_name"]],
            "final_rank": row["final_rank"],
            "match_wins": row["match_wins"],
            "match_losses": row["match_losses"],
            "game_wins": row["game_wins"],
            "game_losses": row["game_losses"],
        }
        for row in team_seasons
    ]

    roster_award_rows = []
    for row in awards:
        roster = roster_lookup.get((row["player_name"], row["season_number"], row["team_name"]))
        if roster is None:
            raise RuntimeError(f"award has no roster entry: {row}")

        roster_award_rows.append({
            "person_id": person_id[row["player_name"]],
            "season_number": row["season_number"],
            "team_id": team_id[row["team_name"]],
            "award_type_id": award_type_id[row["award_type"]],
        })

    sql_parts = [
        "-- Generated by Data Storing/src/make_seed.py",
        "USE mpl_indonesia;",
        "START TRANSACTION;",
        "",
        insert("season", ["season_number", "name", "start_date", "end_date", "prize_pool_usd"], [
            {
                "season_number": row["season_number"],
                "name": row["name"],
                "start_date": row["start_date"],
                "end_date": row["end_date"],
                "prize_pool_usd": row["prize_pool_usd"],
            }
            for row in seasons
        ]),
        insert("season_location", ["season_number", "location"], season_location_rows),
        insert("team", ["team_id", "team_name"], [
            {"team_id": team_id[row["team_name"]], "team_name": row["team_name"]}
            for row in teams
        ]),
        insert("person", ["person_id", "person_name", "nationality"], [
            {
                "person_id": person_id[row["player_name"]],
                "person_name": row["player_name"],
                "nationality": row["nationality"],
            }
            for row in players
        ]),
        insert("award_type", ["award_type_id", "award_name"], [
            {"award_type_id": award_type_id[name], "award_name": name}
            for name in award_names
        ]),
        insert("team_season", ["season_number", "team_id", "final_rank", "match_wins", "match_losses", "game_wins", "game_losses"], team_season_rows),
        insert("matches", ["match_id", "stage", "week", "match_day", "round_name", "season_number"], match_rows),
        insert("roster", ["person_id", "season_number", "team_id", "roster_status", "roster_role"], roster_rows),
        insert("match_team", ["match_id", "team_id", "side", "score"], match_team_rows),
        insert("roster_award", ["person_id", "season_number", "team_id", "award_type_id"], roster_award_rows),
        "COMMIT;",
        "",
    ]

    OUT_FILE.write_text("\n".join(sql_parts), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_FILE}")
    print(f"season={len(seasons)} season_location={len(season_location_rows)} team={len(teams)} person={len(players)} award_type={len(award_names)}")
    print(f"team_season={len(team_season_rows)} match={len(match_rows)} roster={len(roster_rows)}")
    print(f"match_team={len(match_team_rows)} roster_award={len(roster_award_rows)}")


if __name__ == "__main__":
    main()
